[Common]
InitDatabase = 0


[OldDobiDatabase]
DriverName = "mysql"
DataSourceName = "dobi_tra:123###00@tcp(172.16.8.222:3306)/morecoin?charset=utf8&parseTime=True&loc=Local"


[NewDobiDatabase]
    [NewDobiDatabase.Core]
        DriverName = "mysql"
        DataSourceName = "root:123456@tcp(127.0.0.1:3306)/dobi_core?charset=utf8&parseTime=True&loc=Local"
    [NewDobiDatabase.Trade]
        DriverName = "mysql"
        DataSourceName = "root:123456@tcp(127.0.0.1:3306)/dobi_trade?charset=utf8&parseTime=True&loc=Local"


[RedisDatabase]
Addr = "172.16.8.216:6379"
Password = "dobi#!1123Wqs"